//! WGSL test shaders for `craballoc`, written with wgsl-rs.
//!
//! `apply_data_changes` is the port of the old rust-gpu/SPIR-V shader:
//! it applies a queue of slab-encoded data changes to the data slab on
//! the GPU. The wire structs below mirror `craballoc_test_wire_types`
//! slot-for-slot (the CPU test harness keeps using that crate), and the
//! slab serialization is generated by `crabslab::SlabItemExt` from the
//! `#[derive(SlabItem)]` attrs — no hand-written serialization.
//!
//! Counters live in a separate `array<atomic<u32>>` binding: WGSL
//! forbids atomic operations on the plain-`u32` data slab, where the
//! SPIR-V shader used to increment them in place.
use wgsl_rs::wgsl;

#[wgsl(extensions = [crabslab::SlabItemExt])]
pub mod apply_data_changes_shader {
    use crabslab::slab_item::*;
    use wgsl_rs::std::*;

    // ===== Wire-format mirrors =====
    //
    // These must stay slot-identical to `craballoc_test_wire_types`.
    // `Id<T>` mirrors as a plain `u32` field; `Array<T>` mirrors as a
    // `{ start, len }` struct.

    #[derive(Clone, Copy, Debug, Default, PartialEq, Wgsl, SlabItem)]
    pub struct Ints {
        pub first: u32,
        pub second: u32,
    }

    #[derive(Clone, Copy, Debug, Default, PartialEq, Wgsl, SlabItem)]
    pub struct Data {
        pub i: u32,
        pub float: f32,
        pub ints: Ints,
    }

    #[derive(Clone, Copy, Debug, Default, PartialEq, Wgsl, SlabItem)]
    #[repr(u32)]
    pub enum DataChangeTy {
        #[default]
        I,
        Float,
        Ints,
    }

    #[derive(Clone, Copy, Debug, Default, PartialEq, Wgsl, SlabItem)]
    pub struct DataChange {
        pub ty: DataChangeTy,
        pub data: [u32; 3],
    }

    #[derive(Clone, Copy, Debug, Default, PartialEq, Wgsl, SlabItem)]
    pub struct ArrayChange {
        pub i: u32,
        pub change: DataChange,
    }

    /// `Array<Data>`: the data array a change targets.
    #[derive(Clone, Copy, Debug, Default, PartialEq, Wgsl, SlabItem)]
    pub struct ArrayData {
        pub start: u32,
        pub len: u32,
    }

    #[derive(Clone, Copy, Debug, Default, PartialEq, Wgsl, SlabItem)]
    pub struct AnyChangeId {
        pub change_id: u32,
        pub data_array: ArrayData,
    }

    /// `Array<AnyChangeId>`: the invocation's change queue.
    #[derive(Clone, Copy, Debug, Default, PartialEq, Wgsl, SlabItem)]
    pub struct ArrayAnyChangeId {
        pub start: u32,
        pub len: u32,
    }

    #[derive(Clone, Copy, Debug, Default, PartialEq, Wgsl, SlabItem)]
    pub struct ApplyDataChangeInvocation {
        pub changes_ids: ArrayAnyChangeId,
        // The SPIR-V shader incremented these counters atomically in
        // the data slab; the counters now live in COUNTERS, so these
        // slots are kept only to preserve the wire layout.
        pub invocations_id: u32,
        pub invocations_skipped_id: u32,
    }

    // ===== Bindings =====

    storage!(group(0), binding(0), read_write, DATA_SLAB: RuntimeArray<u32>);
    storage!(group(0), binding(1), read_only, CHANGES_SLAB: RuntimeArray<u32>);
    storage!(group(0), binding(2), read_write, COUNTERS: RuntimeArray<Atomic<u32>>);

    /// Apply one queued data change per invocation.
    ///
    /// `COUNTERS[0]` counts successful invocations and `COUNTERS[1]`
    /// counts skipped ones; both must be zeroed by the host before
    /// dispatch.
    #[compute]
    #[workgroup_size(16, 1, 1)]
    pub fn apply_data_changes(#[builtin(global_invocation_id)] global_id: Vec3u) {
        let invocation: ApplyDataChangeInvocation;
        slab_read!(
            ApplyDataChangeInvocation,
            get!(CHANGES_SLAB),
            0u32,
            invocation
        );

        let index = global_id.x;
        if index >= invocation.changes_ids.len {
            atomic_add(&get_mut!(COUNTERS)[1usize], 1u32);
            return;
        }
        atomic_add(&get_mut!(COUNTERS)[0usize], 1u32);

        // Read the change: `AnyChangeId` at
        // `changes_ids.start + index * AnyChangeId::SLAB_SIZE`
        // (mirroring `Array::at`).
        let any_offset = invocation.changes_ids.start + index * AnyChangeId::SLAB_SIZE as u32;
        let any: AnyChangeId;
        slab_read!(AnyChangeId, get!(CHANGES_SLAB), any_offset, any);

        let change: ArrayChange;
        slab_read!(ArrayChange, get!(CHANGES_SLAB), any.change_id, change);

        // Read the target value and apply the change to it. The data
        // array is `Array<Data>`: element `i` lives at
        // `start + i * Data::SLAB_SIZE` (mirroring `Array::at`).
        let data_offset = any.data_array.start + change.i * Data::SLAB_SIZE as u32;
        let mut data: Data;
        slab_read!(Data, get!(DATA_SLAB), data_offset, data);

        if change.change.ty == DataChangeTy::I {
            data.i = change.change.data[0usize];
        } else if change.change.ty == DataChangeTy::Float {
            data.float = bitcast_f32(change.change.data[0usize]);
        } else if change.change.ty == DataChangeTy::Ints {
            data.ints = Ints {
                first: change.change.data[0usize],
                second: change.change.data[1usize],
            };
        }

        slab_write!(Data, get_mut!(DATA_SLAB), data_offset, data);
    }
}
