//! Provides derive macros for `crabslab`.
//!
//! `#[derive(SlabItem)]` generates the Option B trait impl
//! (`SLAB_SIZE`, `type Array`, `to_array`, `from_array`,
//! `array_container`) for structs and enums. The generated impl walks
//! fields with per-element copy loops that mirror wgsl-rs's `slab_copy!`
//! semantics, so the CPU shape matches the GPU shape generated by
//! `crabslab::SlabItemExt`.
//!
//! Types that go through slab I/O (`CpuSlabItem`) must also implement
//! `Clone`, because `to_array` takes the value by value (WGSL has no
//! references).
use quote::quote;
use syn::{
    spanned::Spanned, Data, DataEnum, DataStruct, DeriveInput, Fields, FieldsNamed, FieldsUnnamed,
    Ident, Index, Type, TypeTuple, WherePredicate,
};

enum FieldName {
    Index(Index),
    Ident(Ident),
}

impl FieldName {
    /// The identifier to bind the deserialized field to.
    fn var(&self) -> Ident {
        match self {
            FieldName::Index(i) => Ident::new(&format!("__{}", i.index), i.span),
            FieldName::Ident(field) => field.clone(),
        }
    }
}

struct FieldParams {
    field_tys: Vec<Type>,
    field_names: Vec<FieldName>,
}

impl FieldParams {
    fn new(fields: &syn::punctuated::Punctuated<syn::Field, syn::token::Comma>) -> Self {
        let field_tys: Vec<_> = fields.iter().map(|field| field.ty.clone()).collect();
        let field_names: Vec<_> = fields
            .iter()
            .enumerate()
            .map(|(i, field)| {
                field
                    .ident
                    .clone()
                    .map(FieldName::Ident)
                    .unwrap_or_else(|| {
                        FieldName::Index(Index {
                            index: i as u32,
                            span: field.span(),
                        })
                    })
            })
            .collect();
        Self {
            field_tys,
            field_names,
        }
    }
}

struct StructParams {
    fields: FieldParams,
    /// A `struct Foo;` with no fields at all.
    is_unit: bool,
}

fn get_struct_params(ds: &DataStruct) -> StructParams {
    let empty_punctuated = syn::punctuated::Punctuated::new();
    let (fields, is_unit) = match ds {
        DataStruct {
            fields: Fields::Named(FieldsNamed { named: ref x, .. }),
            ..
        } => (x, false),
        DataStruct {
            fields: Fields::Unnamed(FieldsUnnamed { unnamed: ref x, .. }),
            ..
        } => (x, false),
        DataStruct {
            fields: Fields::Unit,
            ..
        } => (&empty_punctuated, true),
    };

    StructParams {
        fields: FieldParams::new(fields),
        is_unit,
    }
}

struct EnumVariant {
    variant: syn::Variant,
    fields: FieldParams,
}

struct EnumParams {
    variants: Vec<EnumVariant>,
    /// A const-evaluable block computing `1 + max(variant payload sizes)`.
    slab_size: proc_macro2::TokenStream,
}

fn get_enum_params(de: &DataEnum) -> EnumParams {
    let DataEnum {
        enum_token: _,
        brace_token: _,
        variants,
    } = de;
    let variants = variants
        .iter()
        .map(|variant| {
            let empty_fields = syn::punctuated::Punctuated::new();
            let fields = match &variant.fields {
                Fields::Named(FieldsNamed { named: ref x, .. }) => x,
                Fields::Unnamed(FieldsUnnamed { unnamed: ref x, .. }) => x,
                Fields::Unit => &empty_fields,
            };
            let fields = FieldParams::new(fields);
            EnumVariant {
                variant: variant.clone(),
                fields,
            }
        })
        .collect::<Vec<_>>();
    let slab_size_def = quote! {
        let mut __size = 0usize;
    };
    let slab_size_increments = variants
        .iter()
        .map(|variant| {
            let tys = &variant.fields.field_tys;
            if tys.is_empty() {
                quote! {}
            } else {
                quote! {{
                    let __field_size = #( <#tys as crabslab::SlabItem>::SLAB_SIZE )+*;
                    __size += crabslab::__saturating_sub(__field_size,__size);
                }}
            }
        })
        .collect::<Vec<_>>();
    EnumParams {
        slab_size: quote! {
            {
                #slab_size_def
                #(#slab_size_increments)*
                // Add one for the discriminant slot.
                __size + 1
            }
        },
        variants,
    }
}

enum Params {
    Struct(StructParams),
    Enum(EnumParams),
}

fn get_params(input: &DeriveInput) -> syn::Result<Params> {
    match &input.data {
        Data::Struct(ds) => Ok(Params::Struct(get_struct_params(ds))),
        Data::Enum(de) => Ok(Params::Enum(get_enum_params(de))),
        _ => Err(syn::Error::new(
            input.span(),
            "deriving SlabItem does not support unions".to_string(),
        )),
    }
}

/// Per-field copy loop mirroring `slab_copy!(src, 0, dest, i, SIZE)`.
///
/// Emits raw loops (not the macro) so that generated code in downstream
/// crates has no `wgsl-rs` path dependency; the semantics are identical to
/// the `Stmt::SlabCopy` loops the `SlabItemExt` extension generates on the
/// GPU side. The caller must have declared the running index `__i`.
fn field_write_stmts(
    ty: &Type,
    src: proc_macro2::TokenStream,
    dest: proc_macro2::TokenStream,
) -> proc_macro2::TokenStream {
    let size = quote! { <#ty as crabslab::SlabItem>::SLAB_SIZE };
    quote! {
        let __field_arr = <#ty as crabslab::SlabItem>::#src;
        {
            let __src = AsRef::<[u32]>::as_ref(&__field_arr);
            for __j in 0..#size {
                #dest[__i + __j] = __src[__j];
            }
        }
        __i += #size;
    }
}

/// Per-field copy loop mirroring `slab_copy!(slab, i, field_array, 0, SIZE)`.
fn field_read_stmts(ty: &Type, offset: proc_macro2::TokenStream) -> proc_macro2::TokenStream {
    let size = quote! { <#ty as crabslab::SlabItem>::SLAB_SIZE };
    quote! {
        let mut __field_arr = <#ty as crabslab::SlabItem>::array_container();
        {
            let __dst = AsMut::<[u32]>::as_mut(&mut __field_arr);
            for __j in 0..#size {
                __dst[__j] = #offset[__i + __j];
            }
        }
        let __field = <#ty as crabslab::SlabItem>::from_array(__field_arr);
        __i += #size;
    }
}

/// Derives `SlabItem` for a struct.
///
/// ```rust
/// use crabslab::{CpuSlab, GrowableSlab, Id, Slab, SlabItem};
///
/// #[derive(Clone, Copy, Debug, Default, PartialEq, SlabItem)]
/// struct Foo {
///     a: u32,
///     b: u32,
///     c: u32,
/// }
///
/// let foo_one = Foo { a: 1, b: 2, c: 3 };
/// let foo_two = Foo { a: 4, b: 5, c: 6 };
///
/// let mut slab = CpuSlab::new(vec![]);
/// let foo_one_id = slab.append(&foo_one);
/// let foo_two_id = slab.append(&foo_two);
///
/// // Overwrite the second item of the second `Foo`:
/// slab.write(Id::<u32>::new(foo_two_id.inner() + 1), &42);
/// assert_eq!(Foo { a: 4, b: 42, c: 6 }, slab.read(foo_two_id));
/// ```
///
/// No such offsets are derived for enums.
///
/// ```rust
/// use crabslab::{CpuSlab, GrowableSlab, Slab, SlabItem};
///
/// #[derive(Clone, Copy, Debug, Default, PartialEq, SlabItem)]
/// struct Bar {
///     a: u32,
/// }
///
/// #[derive(Clone, Copy, Debug, Default, PartialEq, SlabItem)]
/// enum Baz {
///     #[default]
///     One,
///     Two {
///         a: u32,
///         b: u32,
///     },
///     Three(u32, u32),
///     Four(Bar),
/// }
///
/// assert_eq!(3, Baz::SLAB_SIZE);
///
/// let mut slab = CpuSlab::new(vec![]);
///
/// let one_id = slab.append(&Baz::One);
/// let two_id = slab.append(&Baz::Two { a: 1, b: 2 });
/// let three_id = slab.append(&Baz::Three(3, 4));
/// let four_id = slab.append(&Baz::Four(Bar { a: 5 }));
///
/// assert_eq!(Baz::One, slab.read(one_id));
/// assert_eq!(Baz::Two { a: 1, b: 2 }, slab.read(two_id));
/// assert_eq!(Baz::Three(3, 4), slab.read(three_id));
/// assert_eq!(Baz::Four(Bar { a: 5 }), slab.read(four_id));
/// ```
#[proc_macro_derive(SlabItem, attributes(offsets))]
pub fn derive_from_slab(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let input: DeriveInput = syn::parse_macro_input!(input);

    let gen_offsets_span = input.attrs.iter().find_map(|attr| {
        let path = attr.path();
        if path.is_ident("offsets") {
            Some(path.span())
        } else {
            None
        }
    });

    match get_params(&input) {
        Ok(Params::Struct(p)) => derive_from_slab_struct(input, p, gen_offsets_span.is_some()),
        Ok(Params::Enum(p)) => {
            if let Some(span) = gen_offsets_span {
                syn::Error::new(span, "Deriving field offsets is not supported for enums")
                    .into_compile_error()
                    .into()
            } else {
                derive_from_slab_enum(input, p)
            }
        }
        Err(e) => e.into_compile_error().into(),
    }
}

/// The `type Array` and `array_container` bodies for an impl.
///
/// Concrete types get a fixed-size `[u32; N]` (stack, no allocation) whose
/// length is a const-sum of the field types' slab sizes. Generic types
/// cannot express that length on stable Rust (`generic_const_exprs`), so
/// they fall back to `Vec<u32>`, which satisfies the same
/// `AsRef<[u32]> + AsMut<[u32]>` bounds.
fn array_items(
    is_generic: bool,
    slab_size: proc_macro2::TokenStream,
) -> (proc_macro2::TokenStream, proc_macro2::TokenStream) {
    if is_generic {
        (quote! { Vec<u32> }, quote! { vec![0u32; Self::SLAB_SIZE] })
    } else {
        (quote! { [u32; #slab_size] }, quote! { [0u32; #slab_size] })
    }
}

fn derive_from_slab_enum(input: DeriveInput, params: EnumParams) -> proc_macro::TokenStream {
    let EnumParams {
        variants,
        slab_size,
    } = params;
    let name = &input.ident;
    let is_generic = !input.generics.params.is_empty();

    let field_tys = variants
        .iter()
        .flat_map(|v| v.fields.field_tys.clone())
        .collect::<Vec<_>>();
    let mut generics = input.generics;
    {
        let where_clause = generics.make_where_clause();
        for ty in field_tys.iter() {
            let where_predicate: WherePredicate = syn::parse_quote!(#ty : crabslab::SlabItem);
            where_clause.predicates.push(where_predicate);
        }
        // `from_array` falls back to `Default::default()` for unknown
        // discriminants.
        let where_predicate: WherePredicate = syn::parse_quote!(Self: ::core::default::Default);
        where_clause.predicates.push(where_predicate);
    }
    let (impl_generics, ty_generics, where_clause) = generics.split_for_impl();
    let (array_ty, array_container) = array_items(is_generic, slab_size.clone());

    // Enums serialize as `[discriminant, payload...]`, zero-padded to
    // `SLAB_SIZE`. The discriminant is the variant's index.
    let to_arms: Vec<proc_macro2::TokenStream> = variants
        .iter()
        .enumerate()
        .map(|(vi, variant)| {
            let ident = &variant.variant.ident;
            let discriminant = syn::LitInt::new(&vi.to_string(), variant.variant.span());
            let field_vars: Vec<Ident> = variant
                .fields
                .field_names
                .iter()
                .map(|name| name.var())
                .collect();
            let pat = match variant.variant.fields {
                Fields::Named(_) => quote! { #name::#ident { #(#field_vars),* } },
                Fields::Unnamed(_) => quote! { #name::#ident ( #(#field_vars),* ) },
                Fields::Unit => quote! { #name::#ident },
            };
            let field_stmts: Vec<proc_macro2::TokenStream> = variant
                .fields
                .field_tys
                .iter()
                .zip(field_vars.iter())
                .map(|(ty, var)| {
                    let src = quote! { to_array(#var) };
                    let dest = quote! { AsMut::<[u32]>::as_mut(&mut __dest) };
                    field_write_stmts(ty, src, dest)
                })
                .collect();
            // Only declare the running index when there are fields to walk.
            let index_decl = if variant.fields.field_tys.is_empty() {
                quote! {}
            } else {
                quote! { let mut __i: usize = 1; }
            };
            quote! {
                #pat => {
                    __dest.as_mut()[0] = #discriminant;
                    #index_decl
                    #(#field_stmts)*
                }
            }
        })
        .collect();

    let from_arms: Vec<proc_macro2::TokenStream> = variants
        .iter()
        .enumerate()
        .map(|(vi, variant)| {
            let ident = &variant.variant.ident;
            let discriminant = syn::LitInt::new(&vi.to_string(), variant.variant.span());
            let field_vars: Vec<Ident> = variant
                .fields
                .field_names
                .iter()
                .map(|name| name.var())
                .collect();
            let field_stmts: Vec<proc_macro2::TokenStream> = variant
                .fields
                .field_tys
                .iter()
                .zip(field_vars.iter())
                .map(|(ty, var)| {
                    let mut stmts =
                        field_read_stmts(ty, quote! { AsRef::<[u32]>::as_ref(&__slab) });
                    // Bind the read field to its name.
                    let bind = quote! { let #var = __field; };
                    stmts.extend(bind);
                    stmts
                })
                .collect();
            // Only declare the running index when there are fields to walk.
            let index_decl = if variant.fields.field_tys.is_empty() {
                quote! {}
            } else {
                quote! { let mut __i: usize = 1; }
            };
            let construct = match variant.variant.fields {
                Fields::Named(_) => quote! { #name::#ident { #(#field_vars),* } },
                Fields::Unnamed(_) => quote! { #name::#ident ( #(#field_vars),* ) },
                Fields::Unit => quote! { #name::#ident },
            };
            quote! {
                #discriminant => {
                    #index_decl
                    #(#field_stmts)*
                    #construct
                }
            }
        })
        .collect();

    let output = quote! {
        #[automatically_derived]
        impl #impl_generics crabslab::SlabItem for #name #ty_generics #where_clause
        {
            const SLAB_SIZE: usize = #slab_size;

            type Array = #array_ty;

            fn array_container() -> Self::Array {
                #array_container
            }

            fn to_array(data: Self) -> Self::Array {
                let mut __dest = Self::array_container();
                match data {
                    #(#to_arms)*
                }
                __dest
            }

            fn from_array(__slab: Self::Array) -> Self {
                match AsRef::<[u32]>::as_ref(&__slab)[0] {
                    #(#from_arms)*
                    _ => Default::default(),
                }
            }
        }
    };
    output.into()
}

fn derive_from_slab_struct(
    input: DeriveInput,
    params: StructParams,
    // Whether to generate field offsets
    gen_offsets: bool,
) -> proc_macro::TokenStream {
    let StructParams {
        fields: FieldParams {
            field_tys,
            field_names,
        },
        is_unit,
    } = params;

    let name = &input.ident;
    let is_struct_style = !matches!(field_names.first(), Some(FieldName::Index(_)));
    let is_generic = !input.generics.params.is_empty();
    let mut generics = input.generics;
    {
        let where_clause = generics.make_where_clause();
        for ty in field_tys.iter() {
            let where_predicate: WherePredicate = syn::parse_quote!(#ty : crabslab::SlabItem);
            where_clause.predicates.push(where_predicate);
        }
    }
    let (impl_generics, ty_generics, where_clause) = generics.split_for_impl();

    let n_fields = field_tys.len();
    let slab_size = if n_fields == 0 {
        quote! { 0usize }
    } else {
        quote! { #( <#field_tys as crabslab::SlabItem>::SLAB_SIZE )+* }
    };
    let (array_ty, array_container) = array_items(is_generic, slab_size.clone());

    // Only declare the running index when there are fields to walk.
    let index_decl = if n_fields == 0 {
        quote! {}
    } else {
        quote! { let mut __i: usize = 0; }
    };

    let to_stmts: Vec<proc_macro2::TokenStream> = field_tys
        .iter()
        .zip(field_names.iter())
        .map(|(ty, fname)| {
            let access = match fname {
                FieldName::Index(i) => {
                    let idx = i.index;
                    quote! { data.#idx }
                }
                FieldName::Ident(f) => quote! { data.#f },
            };
            let src = quote! { to_array(#access) };
            let dest = quote! { AsMut::<[u32]>::as_mut(&mut __dest) };
            field_write_stmts(ty, src, dest)
        })
        .collect();

    let from_stmts: Vec<proc_macro2::TokenStream> = field_tys
        .iter()
        .zip(field_names.iter())
        .map(|(ty, fname)| {
            let var = fname.var();
            let mut stmts = field_read_stmts(ty, quote! { AsRef::<[u32]>::as_ref(&__slab) });
            let bind = quote! { let #var = __field; };
            stmts.extend(bind);
            stmts
        })
        .collect();

    let construct = if is_unit {
        quote! { #name }
    } else if is_struct_style {
        let vars: Vec<Ident> = field_names.iter().map(|f| f.var()).collect();
        quote! { #name { #(#vars),* } }
    } else {
        let vars: Vec<Ident> = field_names.iter().map(|f| f.var()).collect();
        quote! { #name ( #(#vars),* ) }
    };

    let mut offset_tys = vec![];
    let mut offsets = vec![];
    for (fname, ty) in field_names.iter().zip(field_tys.iter()) {
        let (offset_of_ident, slab_size_of_ident) = match fname {
            FieldName::Index(i) => (
                Ident::new(&format!("OFFSET_OF_{}", i.index), i.span),
                Ident::new(&format!("SLAB_SIZE_OF_{}", i.index), i.span),
            ),
            FieldName::Ident(field) => (
                Ident::new(
                    &format!("OFFSET_OF_{}", field.to_string().to_uppercase()),
                    field.span(),
                ),
                Ident::new(
                    &format!("SLAB_SIZE_OF_{}", field.to_string().to_uppercase()),
                    field.span(),
                ),
            ),
        };
        offsets.push(quote! {
            pub const #offset_of_ident: crabslab::offset::Offset<#ty, Self> = {
                crabslab::offset::Offset::new(
                    #(<#offset_tys as crabslab::SlabItem>::SLAB_SIZE+)*
                    0
                )
            };
            pub const #slab_size_of_ident: usize = {
                <#ty as crabslab::SlabItem>::SLAB_SIZE
            };
        });
        offset_tys.push(ty.clone());
    }

    let offsets_output = if gen_offsets {
        quote! {
            #[automatically_derived]
            /// Offsets into the slab buffer for each field.
            impl #impl_generics #name #ty_generics {
                #(#offsets)*
            }
        }
    } else {
        quote! {}
    };

    let output = quote! {
        #[automatically_derived]
        impl #impl_generics crabslab::SlabItem for #name #ty_generics #where_clause
        {
            const SLAB_SIZE: usize = #slab_size;

            type Array = #array_ty;

            fn array_container() -> Self::Array {
                #array_container
            }

            fn to_array(data: Self) -> Self::Array {
                let mut __dest = Self::array_container();
                #index_decl
                #(#to_stmts)*
                __dest
            }

            fn from_array(__slab: Self::Array) -> Self {
                #index_decl
                #(#from_stmts)*
                #construct
            }
        }
        #offsets_output
    };
    output.into()
}

#[proc_macro]
pub fn impl_slabitem_tuples(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let tuple: TypeTuple = syn::parse_macro_input!(input);
    let tys = tuple.elems.iter().collect::<Vec<_>>();
    let indices = tys
        .iter()
        .enumerate()
        .map(|(i, _)| Index::from(i))
        .collect::<Vec<_>>();

    // Tuples are generic over their element types, so `type Array` cannot
    // be a fixed-size array on stable Rust (`generic_const_exprs`) — use
    // the `Vec<u32>` escape hatch.
    let to_stmts: Vec<proc_macro2::TokenStream> = tys
        .iter()
        .zip(indices.iter())
        .map(|(ty, index)| {
            let src = quote! { to_array(data.#index) };
            let dest = quote! { AsMut::<[u32]>::as_mut(&mut __dest) };
            field_write_stmts(ty, src, dest)
        })
        .collect();
    let from_vars: Vec<Ident> = tys
        .iter()
        .enumerate()
        .map(|(i, ty)| Ident::new(&format!("__{i}"), ty.span()))
        .collect();
    let from_stmts: Vec<proc_macro2::TokenStream> = tys
        .iter()
        .zip(from_vars.iter())
        .map(|(ty, var)| {
            let mut stmts = field_read_stmts(ty, quote! { AsRef::<[u32]>::as_ref(&__slab) });
            let bind = quote! { let #var = __field; };
            stmts.extend(bind);
            stmts
        })
        .collect();

    let output = quote! {
        impl<#(#tys),*> crabslab::SlabItem for #tuple
        where
            #(#tys: crabslab::SlabItem),*,
        {
            const SLAB_SIZE: usize = {
                #( <#tys as crabslab::SlabItem>::SLAB_SIZE )+*
            };

            type Array = Vec<u32>;

            fn array_container() -> Self::Array {
                vec![0u32; Self::SLAB_SIZE]
            }

            fn to_array(data: Self) -> Self::Array {
                let mut __dest = Self::array_container();
                let mut __i: usize = 0;
                #(#to_stmts)*
                __dest
            }

            fn from_array(__slab: Self::Array) -> Self {
                let mut __i: usize = 0;
                #(#from_stmts)*
                (#(#from_vars,)*)
            }
        }
    };
    output.into()
}
