//! The living experiment fixture for GPU-side slab serialization.
//!
//! Everything here is exercised end-to-end: `#[derive(SlabItem)]`
//! structs get their WGSL serialization impls generated by
//! [`crate::SlabItemExt`] (the derives run after `#[wgsl]`, so the
//! transpiler alone can't see them), the primitive methods
//! (`u32__1to_array`, …) are imported from [`crate::slab_item`], and
//! `slab_read!`/`slab_write!` are lowered by the extension while the
//! CPU compiles them through the `slab_macros!` `macro_rules!`.
use wgsl_rs::wgsl;

#[wgsl(extensions = [crate::SlabItemExt])]
pub mod slab {
    use crate::slab_item::*;
    use wgsl_rs::std::*;

    /// A struct of primitive fields.
    #[derive(Clone, Copy, Debug, Default, PartialEq, Wgsl, SlabItem)]
    pub struct Bar {
        pub value: f32,
        pub flag: bool,
    }

    /// A struct covering all three field shapes the extension
    /// generates: a primitive, a nested slab struct, and an array of
    /// primitives (unrolled element-wise).
    #[derive(Clone, Copy, Debug, Default, PartialEq, Wgsl, SlabItem)]
    pub struct Foo {
        pub count: u32,
        pub inner: Bar,
        pub tags: [u32; 3],
    }

    /// The innermost of the three-level nesting chain
    /// `Deep → Middle → Leaf`.
    #[derive(Clone, Copy, Debug, Default, PartialEq, Wgsl, SlabItem)]
    pub struct Leaf {
        pub value: f32,
    }

    /// The middle level: recursion through `Leaf`'s generated methods.
    #[derive(Clone, Copy, Debug, Default, PartialEq, Wgsl, SlabItem)]
    pub struct Middle {
        pub id: u32,
        pub leaf: Leaf,
    }

    /// The outermost of the three-level chain: recursion through
    /// `Middle`'s generated methods, which recurse through `Leaf`'s.
    #[derive(Clone, Copy, Debug, Default, PartialEq, Wgsl, SlabItem)]
    pub struct Deep {
        pub tag: u32,
        pub middle: Middle,
    }

    /// A fieldless enum — the extension serializes unit-variant enums
    /// as their variant position in one slot.
    #[derive(Clone, Copy, Debug, Default, PartialEq, Wgsl, SlabItem)]
    #[repr(u32)]
    pub enum Kind {
        #[default]
        Alpha,
        Beta,
    }

    /// A struct with an enum field: `Kind__1SLAB_SIZE` contributes to
    /// the const-sum like any other slab item type.
    #[derive(Clone, Copy, Debug, Default, PartialEq, Wgsl, SlabItem)]
    pub struct Tagged {
        pub kind: Kind,
        pub weight: u32,
    }

    storage!(group(0), binding(0), read_write, SLAB: RuntimeArray<u32>);

    #[compute]
    #[workgroup_size(8)]
    pub fn main(#[builtin(local_invocation_index)] _x: u32) {
        // Manual form: the parser's builtin `slab_copy!` plus the
        // extension-generated mangled methods.
        let mut foo_array = Foo::array_container();
        slab_copy!(get!(SLAB), 0, foo_array, 0, Foo::SLAB_SIZE);

        let mut d = Foo::from_array(foo_array);
        d.count += 1;
        d.inner.flag = true;

        let foo_slab = Foo::to_array(d);
        slab_copy!(foo_slab, 0, get_mut!(SLAB), 0, Foo::SLAB_SIZE);

        // Lowered form: `slab_read!`/`slab_write!` captured as
        // `Stmt::Macro` and lowered by `SlabItemExt`. The destination
        // is declared here, like the CPU macro requires.
        let mut e: Foo;
        slab_read!(Foo, get!(SLAB), 0u32, e);
        e.count += 1;
        slab_write!(Foo, get_mut!(SLAB), 0u32, e);
    }
}

/// A module that serializes a slab struct IMPORTED from another module
/// — verifying the cross-module constraint (hw9.3): the generated
/// `Wrapper__1SLAB_SIZE` and `Wrapper__1to_array` reference
/// `Deep__1SLAB_SIZE` / `Deep__1to_array`, which only exist in the
/// assembled WGSL because the defining module (`slab`) also runs
/// `SlabItemExt`. See the extension's module docs.
#[wgsl(extensions = [crate::SlabItemExt])]
pub mod cross_module {
    use crate::slab_item::*;
    use crate::wgsl_impl::slab::*;
    use wgsl_rs::std::*;

    /// Wraps the three-level `Deep` chain from the experiment module.
    #[derive(Clone, Copy, Debug, Default, PartialEq, Wgsl, SlabItem)]
    pub struct Wrapper {
        pub serial: u32,
        pub deep: Deep,
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod test {
    use super::cross_module;
    use super::slab::*;
    use crate::{CpuSlab, GrowableSlab, Slab, SlabItem};

    /// The CPU derive and the GPU extension must agree on sizes — the
    /// generated WGSL const-sums mirror these.
    #[test]
    fn derived_slab_sizes() {
        assert_eq!(2, Bar::SLAB_SIZE);
        assert_eq!(1 + 2 + 3, Foo::SLAB_SIZE);
        assert_eq!(1, Leaf::SLAB_SIZE);
        assert_eq!(2, Middle::SLAB_SIZE);
        assert_eq!(3, Deep::SLAB_SIZE);
        assert_eq!(1, Kind::SLAB_SIZE);
        assert_eq!(2, Tagged::SLAB_SIZE);
        assert_eq!([0u32; 2], Bar::array_container());
        assert_eq!([0u32; 6], Foo::array_container());
    }

    /// Round-trip the derived structs through a CPU slab — the same
    /// structs the extension serializes on the GPU.
    #[test]
    fn derived_cpu_round_trip() {
        let foo = Foo {
            count: 42,
            inner: Bar {
                value: 3.5,
                flag: true,
            },
            tags: [1, 2, 3],
        };
        let mut slab = CpuSlab::new(vec![]);
        let id = slab.append(&foo);
        assert_eq!(foo, slab.read(id));
    }

    /// Three levels of nesting round-trip on the CPU — the same shape
    /// the extension recurses through on the GPU.
    #[test]
    fn derived_deep_round_trip() {
        let deep = Deep {
            tag: 3,
            middle: Middle {
                id: 99,
                leaf: Leaf { value: -2.5 },
            },
        };
        let mut slab = CpuSlab::new(vec![]);
        let id = slab.append(&deep);
        assert_eq!(deep, slab.read(id));
    }

    /// The cross-module `Wrapper` round-trips on the CPU; its derive
    /// references `Deep`'s trait impl, which lives in the other
    /// module.
    #[test]
    fn derived_cross_module_round_trip() {
        let wrapper = cross_module::Wrapper {
            serial: 11,
            deep: Deep {
                tag: 4,
                middle: Middle {
                    id: 12,
                    leaf: Leaf { value: 0.25 },
                },
            },
        };
        let mut slab = CpuSlab::new(vec![]);
        let id = slab.append(&wrapper);
        assert_eq!(wrapper, slab.read(id));
    }

    /// A fieldless enum serializes as one slot (its variant position)
    /// in both worlds, including as a struct field.
    #[test]
    fn derived_enum_round_trip() {
        let tagged = Tagged {
            kind: Kind::Beta,
            weight: 9,
        };
        let mut slab = CpuSlab::new(vec![]);
        let id = slab.append(&tagged);
        assert_eq!(tagged, slab.read(id));

        // The wire form is the variant position.
        let raw = slab.as_ref();
        assert_eq!([1u32, 9], [raw[0], raw[1]]);
    }

    /// The dual-world macros round-trip the derived structs through a
    /// plain `[u32; N]`, including at a nonzero offset.
    #[test]
    fn macros_round_trip_array() {
        let foo = Foo {
            count: 7,
            inner: Bar {
                value: 1.5,
                flag: true,
            },
            tags: [4, 5, 6],
        };

        let mut slab = [0u32; Foo::SLAB_SIZE];
        slab_write!(Foo, slab, 0, foo);
        let read: Foo;
        slab_read!(Foo, slab, 0, read);
        assert_eq!(foo, read);

        // A nonzero offset: the surrounding slots stay untouched.
        let mut slab = [0u32; Foo::SLAB_SIZE + 3];
        slab_write!(Foo, slab, 2, foo);
        assert_eq!(0, slab[0]);
        assert_eq!(0, slab[1]);
        assert_eq!(0, slab[Foo::SLAB_SIZE + 2]);
        let read: Foo;
        slab_read!(Foo, slab, 2, read);
        assert_eq!(foo, read);
    }

    #[test]
    fn generates_wgsl() {
        let source = WGSL_SOURCE.wgsl_source().unwrap();
        eprintln!("{source}");

        // The primitive impls come from the imported `slab_item` module
        // and render with the mangled `Type__1member` names.
        assert!(
            source.contains("const u32__1SLAB_SIZE: u32 = 1u;"),
            "expected u32__1SLAB_SIZE, got:\n{source}"
        );
        assert!(
            source.contains("fn u32__1to_array("),
            "expected u32__1to_array, got:\n{source}"
        );
        assert!(
            source.contains("fn u32__1from_array("),
            "expected u32__1from_array, got:\n{source}"
        );

        // Struct impls render `SLAB_SIZE` as a const-sum expression
        // over the field types' mangled consts, not a literal.
        assert!(
            source.contains("const Bar__1SLAB_SIZE: u32 = (f32__1SLAB_SIZE + bool__1SLAB_SIZE);"),
            "expected Bar__1SLAB_SIZE const-sum, got:\n{source}"
        );
        assert!(
            source.contains(
                "const Foo__1SLAB_SIZE: u32 = \
                 ((u32__1SLAB_SIZE + Bar__1SLAB_SIZE) + (3u * u32__1SLAB_SIZE));"
            ),
            "expected Foo__1SLAB_SIZE const-sum, got:\n{source}"
        );
        assert!(
            source.contains("fn Bar__1to_array("),
            "expected Bar__1to_array, got:\n{source}"
        );
        assert!(
            source.contains("fn Bar__1from_array("),
            "expected Bar__1from_array, got:\n{source}"
        );
        assert!(
            source.contains("fn Foo__1to_array("),
            "expected Foo__1to_array, got:\n{source}"
        );
        assert!(
            source.contains("fn Foo__1from_array("),
            "expected Foo__1from_array, got:\n{source}"
        );

        // The offset-corrected lowering: `to_array` writes `dest[i + _i]`
        // from the field slab at `0u`, and `from_array` reads `slab[i + _i]`
        // into the field array at `0u`.
        assert!(
            source.contains("dest[i + _i] = value_slab[0u + _i];"),
            "expected offset-on-dest to_array copy, got:\n{source}"
        );
        assert!(
            source.contains("value_array[0u + _i] = slab[i + _i];"),
            "expected offset-on-src from_array copy, got:\n{source}"
        );

        // Nested structs recurse through the field type's mangled
        // methods.
        assert!(
            source.contains("let inner_slab = Bar__1to_array(data.inner);"),
            "expected nested Bar__1to_array call, got:\n{source}"
        );
        assert!(
            source.contains("let inner = Bar__1from_array(inner_array);"),
            "expected nested Bar__1from_array call, got:\n{source}"
        );

        // Three levels of nesting: each const-sum references the next
        // level's mangled const, and the walks recurse level by level.
        // A single-field struct's SLAB_SIZE is the bare TypePath.
        assert!(
            source.contains("const Leaf__1SLAB_SIZE: u32 = f32__1SLAB_SIZE;"),
            "expected Leaf__1SLAB_SIZE TypePath form, got:\n{source}"
        );
        assert!(
            source
                .contains("const Middle__1SLAB_SIZE: u32 = (u32__1SLAB_SIZE + Leaf__1SLAB_SIZE);"),
            "expected Middle__1SLAB_SIZE const-sum, got:\n{source}"
        );
        assert!(
            source
                .contains("const Deep__1SLAB_SIZE: u32 = (u32__1SLAB_SIZE + Middle__1SLAB_SIZE);"),
            "expected Deep__1SLAB_SIZE const-sum, got:\n{source}"
        );
        assert!(
            source.contains("let leaf_slab = Leaf__1to_array(data.leaf);"),
            "expected Middle -> Leaf to_array recursion, got:\n{source}"
        );
        assert!(
            source.contains("let middle_slab = Middle__1to_array(data.middle);"),
            "expected Deep -> Middle to_array recursion, got:\n{source}"
        );
        assert!(
            source.contains("let leaf = Leaf__1from_array(leaf_array);"),
            "expected Middle -> Leaf from_array recursion, got:\n{source}"
        );
        assert!(
            source.contains("let middle = Middle__1from_array(middle_array);"),
            "expected Deep -> Middle from_array recursion, got:\n{source}"
        );

        // Fieldless enums serialize their variant position in one slot,
        // and enum-typed struct fields take the generic TypePath path.
        assert!(
            source.contains("const Kind__1SLAB_SIZE: u32 = 1u;"),
            "expected Kind__1SLAB_SIZE, got:\n{source}"
        );
        assert!(
            source
                .contains("const Tagged__1SLAB_SIZE: u32 = (Kind__1SLAB_SIZE + u32__1SLAB_SIZE);"),
            "expected Tagged__1SLAB_SIZE const-sum, got:\n{source}"
        );
        assert!(
            source.contains("let kind_slab = Kind__1to_array(data.kind);"),
            "expected Tagged -> Kind to_array call, got:\n{source}"
        );
        assert!(
            source.contains("let kind = Kind__1from_array(kind_array);"),
            "expected Tagged -> Kind from_array call, got:\n{source}"
        );

        // Array fields unroll one to_array/from_array pair per element.
        assert!(
            source.contains("let tags_slab_0 = u32__1to_array(data.tags[0u]);"),
            "expected unrolled array element to_array, got:\n{source}"
        );
        assert!(
            source.contains("let tags_2 = u32__1from_array(tags_array_2);"),
            "expected unrolled array element from_array, got:\n{source}"
        );

        // `slab_read!`/`slab_write!` lower to array_container + copy +
        // from_array / to_array + copy sequences.
        assert!(
            source.contains("Foo__1from_array(slab_read_buf)"),
            "expected lowered slab_read!, got:\n{source}"
        );
        assert!(
            source.contains("Foo__1to_array(e)"),
            "expected lowered slab_write!, got:\n{source}"
        );

        // No unlowered macros survive to the rendered source.
        assert!(
            !source.contains("slab_copy!"),
            "slab_copy! should have been lowered, got:\n{source}"
        );
        assert!(
            !source.contains("slab_read!"),
            "slab_read! should have been lowered, got:\n{source}"
        );
        assert!(
            !source.contains("slab_write!"),
            "slab_write! should have been lowered, got:\n{source}"
        );
    }

    /// The cross-module module's generated impl references the IMPORTED
    /// struct's mangled methods (`Deep__1SLAB_SIZE`, `Deep__1to_array`),
    /// which exist in the assembled WGSL because the imported module
    /// also runs `SlabItemExt` — the hw9.3 constraint, verified
    /// end-to-end (the module's own `__validate_wgsl` naga check covers
    /// the assembled source).
    #[test]
    fn generates_cross_module_wgsl() {
        let source = cross_module::WGSL_SOURCE.wgsl_source().unwrap();
        eprintln!("{source}");

        assert!(
            source
                .contains("const Wrapper__1SLAB_SIZE: u32 = (u32__1SLAB_SIZE + Deep__1SLAB_SIZE);"),
            "expected Wrapper__1SLAB_SIZE const-sum, got:\n{source}"
        );
        assert!(
            source.contains("let deep_slab = Deep__1to_array(data.deep);"),
            "expected Wrapper -> Deep to_array recursion, got:\n{source}"
        );
        assert!(
            source.contains("let deep = Deep__1from_array(deep_array);"),
            "expected Wrapper -> Deep from_array recursion, got:\n{source}"
        );
        // The referenced methods come from the imported module's
        // source, not this module's.
        assert!(
            source.contains("fn Deep__1to_array("),
            "expected imported Deep__1to_array to assemble in, got:\n{source}"
        );
        assert!(
            source
                .contains("const Deep__1SLAB_SIZE: u32 = (u32__1SLAB_SIZE + Middle__1SLAB_SIZE);"),
            "expected imported Deep__1SLAB_SIZE to assemble in, got:\n{source}"
        );
        // Imported transitively through Deep: the primitives.
        assert!(
            source.contains("fn u32__1to_array("),
            "expected transitive primitive import, got:\n{source}"
        );
    }
}
