//! The living experiment fixture for GPU-side slab serialization.
//!
//! Everything here is exercised end-to-end: `#[derive(SlabItem)]`
//! structs get their WGSL serialization impls generated by
//! [`crate::SlabItemExt`] (the derives run after `#[wgsl]`, so the
//! transpiler alone can't see them), the primitive methods
//! (`u32__1to_array`, …) are imported from [`crate::slab_item`], and
//! `slab_read!`/`slab_write!` are lowered by the extension while the
//! CPU compiles them through the `slab_macros!` `macro_rules!`.
use wgsl_rs::wgsl;

#[wgsl(extensions = [crate::SlabItemExt])]
pub mod slab {
    use crate::slab_item::*;
    use wgsl_rs::std::*;

    /// A struct of primitive fields.
    #[derive(Clone, Copy, Debug, Default, PartialEq, Wgsl, SlabItem)]
    pub struct Bar {
        pub value: f32,
        pub flag: bool,
    }

    /// A struct covering all three field shapes the extension
    /// generates: a primitive, a nested slab struct, and an array of
    /// primitives (unrolled element-wise).
    #[derive(Clone, Copy, Debug, Default, PartialEq, Wgsl, SlabItem)]
    pub struct Foo {
        pub count: u32,
        pub inner: Bar,
        pub tags: [u32; 3],
    }

    storage!(group(0), binding(0), read_write, SLAB: RuntimeArray<u32>);

    #[compute]
    #[workgroup_size(8)]
    pub fn main(#[builtin(local_invocation_index)] _x: u32) {
        // Manual form: the parser's builtin `slab_copy!` plus the
        // extension-generated mangled methods.
        let mut foo_array = Foo::array_container();
        slab_copy!(get!(SLAB), 0, foo_array, 0, Foo::SLAB_SIZE);

        let mut d = Foo::from_array(foo_array);
        d.count += 1;
        d.inner.flag = true;

        let foo_slab = Foo::to_array(d);
        slab_copy!(foo_slab, 0, get_mut!(SLAB), 0, Foo::SLAB_SIZE);

        // Lowered form: `slab_read!`/`slab_write!` captured as
        // `Stmt::Macro` and lowered by `SlabItemExt`. The destination
        // is declared here, like the CPU macro requires.
        let mut e: Foo;
        slab_read!(Foo, get!(SLAB), 0u32, e);
        e.count += 1;
        slab_write!(Foo, get_mut!(SLAB), 0u32, e);
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod test {
    use super::slab::*;
    use crate::{CpuSlab, GrowableSlab, Slab, SlabItem};

    /// The CPU derive and the GPU extension must agree on sizes — the
    /// generated WGSL const-sums mirror these.
    #[test]
    fn derived_slab_sizes() {
        assert_eq!(2, Bar::SLAB_SIZE);
        assert_eq!(1 + 2 + 3, Foo::SLAB_SIZE);
        assert_eq!([0u32; 2], Bar::array_container());
        assert_eq!([0u32; 6], Foo::array_container());
    }

    /// Round-trip the derived structs through a CPU slab — the same
    /// structs the extension serializes on the GPU.
    #[test]
    fn derived_cpu_round_trip() {
        let foo = Foo {
            count: 42,
            inner: Bar {
                value: 3.5,
                flag: true,
            },
            tags: [1, 2, 3],
        };
        let mut slab = CpuSlab::new(vec![]);
        let id = slab.append(&foo);
        assert_eq!(foo, slab.read(id));
    }

    #[test]
    fn generates_wgsl() {
        let source = WGSL_SOURCE.wgsl_source().unwrap();
        eprintln!("{source}");

        // The primitive impls come from the imported `slab_item` module
        // and render with the mangled `Type__1member` names.
        assert!(
            source.contains("const u32__1SLAB_SIZE: u32 = 1u;"),
            "expected u32__1SLAB_SIZE, got:\n{source}"
        );
        assert!(
            source.contains("fn u32__1to_array("),
            "expected u32__1to_array, got:\n{source}"
        );
        assert!(
            source.contains("fn u32__1from_array("),
            "expected u32__1from_array, got:\n{source}"
        );

        // Struct impls render `SLAB_SIZE` as a const-sum expression
        // over the field types' mangled consts, not a literal.
        assert!(
            source.contains("const Bar__1SLAB_SIZE: u32 = (f32__1SLAB_SIZE + bool__1SLAB_SIZE);"),
            "expected Bar__1SLAB_SIZE const-sum, got:\n{source}"
        );
        assert!(
            source.contains(
                "const Foo__1SLAB_SIZE: u32 = \
                 ((u32__1SLAB_SIZE + Bar__1SLAB_SIZE) + (3u * u32__1SLAB_SIZE));"
            ),
            "expected Foo__1SLAB_SIZE const-sum, got:\n{source}"
        );
        assert!(
            source.contains("fn Bar__1to_array("),
            "expected Bar__1to_array, got:\n{source}"
        );
        assert!(
            source.contains("fn Bar__1from_array("),
            "expected Bar__1from_array, got:\n{source}"
        );
        assert!(
            source.contains("fn Foo__1to_array("),
            "expected Foo__1to_array, got:\n{source}"
        );
        assert!(
            source.contains("fn Foo__1from_array("),
            "expected Foo__1from_array, got:\n{source}"
        );

        // The offset-corrected lowering: `to_array` writes `dest[i + _i]`
        // from the field slab at `0u`, and `from_array` reads `slab[i + _i]`
        // into the field array at `0u`.
        assert!(
            source.contains("dest[i + _i] = value_slab[0u + _i];"),
            "expected offset-on-dest to_array copy, got:\n{source}"
        );
        assert!(
            source.contains("value_array[0u + _i] = slab[i + _i];"),
            "expected offset-on-src from_array copy, got:\n{source}"
        );

        // Nested structs recurse through the field type's mangled
        // methods.
        assert!(
            source.contains("let inner_slab = Bar__1to_array(data.inner);"),
            "expected nested Bar__1to_array call, got:\n{source}"
        );
        assert!(
            source.contains("let inner = Bar__1from_array(inner_array);"),
            "expected nested Bar__1from_array call, got:\n{source}"
        );

        // Array fields unroll one to_array/from_array pair per element.
        assert!(
            source.contains("let tags_slab_0 = u32__1to_array(data.tags[0u]);"),
            "expected unrolled array element to_array, got:\n{source}"
        );
        assert!(
            source.contains("let tags_2 = u32__1from_array(tags_array_2);"),
            "expected unrolled array element from_array, got:\n{source}"
        );

        // `slab_read!`/`slab_write!` lower to array_container + copy +
        // from_array / to_array + copy sequences.
        assert!(
            source.contains("Foo__1from_array(slab_read_buf)"),
            "expected lowered slab_read!, got:\n{source}"
        );
        assert!(
            source.contains("Foo__1to_array(e)"),
            "expected lowered slab_write!, got:\n{source}"
        );

        // No unlowered macros survive to the rendered source.
        assert!(
            !source.contains("slab_copy!"),
            "slab_copy! should have been lowered, got:\n{source}"
        );
        assert!(
            !source.contains("slab_read!"),
            "slab_read! should have been lowered, got:\n{source}"
        );
        assert!(
            !source.contains("slab_write!"),
            "slab_write! should have been lowered, got:\n{source}"
        );
    }
}
