[package]
name = "craballoc-test-shaders"
version = "0.1.0"
edition = "2021"
description = "WGSL test shaders for craballoc, written with wgsl-rs"
repository = "https://github.com/schell/crabslab"
license = "MIT OR Apache-2.0"

[dependencies]
crabslab = { path = "../crabslab", default-features = false }
wgsl-rs.workspace = true